# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_redgreen_wrappers", use_symbols = TRUE, package_name = "redgreen")

#' @docType package
#' @usage NULL
#' @useDynLib redgreen, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
redgreen <- function(value, diff) .Call(wrap__redgreen, value, diff)


# nolint end
